name: mobile
description: "LAYLA Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ícones do estilo iOS
  cupertino_icons: ^1.0.8

  # Comunicação Bluetooth Low Energy com o ESP32
  flutter_reactive_ble: ^5.3.1

  # Gerenciamento de permissões (Bluetooth e Localização no Android)
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true